[package]
name = "rust_tokenizers"
version = "0.21.0"
edition = "2018"

[lib]
name = "rust_tokenizers"
crate-type = ["cdylib"]

[dependencies]
tokenizers = { version = "0.21.0", default-features = false, features = ["onig"] }
